<div class="justify-content-center align-items-center">
<form action="?page=carsEdit" method="post">
    <div class="row justify-content-center align-items-center">
        <div class="col text-center">
            <img src="<?php echo $config["ICONS_PATH"].'icons8-truck-100.png'?>" alt="Carro">
        </div>
        <div class="col">
            <h1>Novo Carro</h1>
            <div class="form-group">
                <label for="plate">Matrícula</label>
                <input type="text" class="form-control" name="plate" id="plate"  value="<?php echo (!empty($car["plate"]))?$car["plate"]:'';?>" placeholder="Introduza a matrícula">
            </div>
            <div class="form-group">
                <label for="maker">Marca</label>
                <input type="text" class="form-control" name="maker" id="maker"  value="<?php echo (!empty($car["maker"]))?$car["maker"]:'';?>" placeholder="Introduza a marca">
            </div>
            <div class="form-group">
                <label for="model">Modelo</label>
                <input type="text" class="form-control" name="model" id="model"  value="<?php echo (!empty($car["model"]))?$car["model"]:'';?>" placeholder="Introduza o modelo">
            </div>
            <div class="form-group">
                <label for="number">Número</label>
                <input type="number" class="form-control" name="number" id="number" value="<?php echo (!empty($car["number"]))?$car["number"]:'';?>" 
                    placeholder="Introduza o número de identificação">
            </div>
            <input type="number" name="id" id="id" value="<?php echo (!empty($car))?$car["id"]:'';?>" class="d-none">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </div>
</form>
</div>