<form action="?page=daily" method="post">
<div class="mt-1 card-body row no-gutters align-items-center">
    <div class="col-auto">
        <i class="fas fa-search h5 text-body"></i>
    </div>
    <!--end of col-->
    <div class="col-sm-4">
        <input value="<?php echo $search?>" name="search" id="search" class="form-control form-control-borderless" type="search" placeholder="Indique um critério de pesquisa...">
    </div>
    <!--end of col-->
    <div class="col-sm-5">
        <button class="btn btn-primary" name="submitbutton" value="search" type="submit">Pesquisar</button>
        <button name="submitbutton" value="clear" class="btn btn bg-light" type="submit">Limpar</button>
    </div>
    <!--end of col-->
</div>
</form>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Dia</th>
                <th scope="col">Funcionários</th>
                <th scope="col">Total</th>
                <th scope="col">Carros</th>
                <th scope="col">Total</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($dailies['list'] AS $daily) {
                    echo '<tr>';
                    echo '<td>'.$daily['currdate'].'</td>';
                    echo '<td>'.(empty($daily['workers'])?'Não tem...':$daily['workers']).'</td>';
                    echo '<td>'.$daily['workerstotal'].'</td>';
                    echo '<td>'.(empty($daily['cars'])?'Não tem...':$daily['cars']).'</td>';
                    echo '<td>'.$daily['carstotal'].'</td>';
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
    <?php            
        if(empty($dailies['list'])){
            echo '<tr><td><div class="blank-slate">Não há Mudanças registadas...</div></td></tr>';
        }
    ?>

    <nav aria-label="Page navigation" class="pagination-nav">
        <ul class="pagination">
            <?php 
                $maxpage = ceil($dailies['count']/$linecount);
                if($listpage>0){
                    echo '<li class="page-item">
                    <a class="page-link" href="?page=daily&listpage='.($listpage-1).'" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                    </li>';
                }
                for($i=1;$i<=$maxpage;$i++){
                    echo '<li class="page-item"><a class="page-link '.($i==$listpage+1?'page-link-active':'').'" href="?page=daily&listpage='.($i-1).'">'.$i.'</a></li>';
                }
                if(($listpage+1)<$maxpage){
                    echo '
                    <li class="page-item">
                    <a class="page-link" href="?page=daily&listpage='.($listpage+1).'" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                    </li>';
                }
            ?>
        </ul>
    </nav>
</div>