
  <div class="alert alert-success alert-dismissible fade" role="alert">
      Mudança atualizada com <strong>sucesso</strong>!
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
  </div>
  <div class="alert alert-danger alert-dismissible fade" role="alert">
      Ocorreu um erro na atualização da mudança!
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
  </div>
  <div id='calendar-container' class="mb-5">
    <div>
      <ul id="colorlegend"><li style="color:green;">Pago</li><li style="color:#5c0a0a;">Por pagar</li><li style="color:#0077ff;">A decorrer</li><li style="color:#111251;">Futura</li><li style="color:gray;">Cancelada</li></ul>
    </div>
    <div id='calendar'></div>
  </div>

<style>
  .btn-group {
    width:auto;
  }
  .btn-group>.btn {
    width:auto;
  }
</style>
<script>
  function updateEventOnDB(info) {
    var startDate = moment(info.event.start).tz('Europe/Lisbon').format('YYYY-MM-DD HH:mm:ss');
    var endDate = moment(info.event.end).tz('Europe/Lisbon').format('YYYY-MM-DD HH:mm:ss');
    var id = info.event.id;
    jQuery.ajax({
      type: "POST",
      url: 'schedulesCalendarEventUpdate.php',
      dataType: 'json',
      data: {functionname: 'updateEvent', arguments: [startDate,endDate,id]},

      success: function (obj, textstatus) {
                    if( !('error' in obj) ) {
                        console.log(obj.result);
                        $('.alert-success').addClass('show');
                    }
                    else {
                        console.log(obj.error);
                        $('.alert-danger').addClass('show');
                    }
              }
    });
  }

  function updateEventEndOnDB(info) {
    var endDate = moment(info.event.end).tz('Europe/Lisbon').format('YYYY-MM-DD HH:mm:ss');
    var id = info.event.id;
    jQuery.ajax({
      type: "POST",
      url: 'schedulesCalendarEventUpdate.php',
      dataType: 'json',
      data: {functionname: 'updateEventEnd', arguments: [endDate,id]},

      success: function (obj, textstatus) {
                    if( !('error' in obj) ) {
                        console.log(obj.result);
                        $('.alert-success').addClass('show');
                    }
                    else {
                        console.log(obj.error);
                        $('.alert-danger').addClass('show');
                    }
              },
      error: function(jqXHR, textStatus, errorThrown ) {
        //console.log(jqXHR);
        //console.log(textStatus);
        //console.log(errorThrown);
      },
      complete: function() {
        //console.log('ajax finished');
      }
    });
  }

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var scrollTime = moment().format("HH:mm:ss");
    window.jscalendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'interaction', 'dayGrid', 'timeGrid', 'list', 'bootstrap' ],
      themeSystem: 'bootstrap',
      views: {
        dayGridMonth: {
          eventLimit: 10 // adjust to 6 only for timeGridWeek/timeGridDay
        }
      },
      height: 'parent',
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,dayGridWeek,dayGridDay,listWeek'
      },
      displayEventTime:true,
      displayEventEnd:true,
      eventAllow: function(){
        return true;
      }, // to be reviewed. we should have a function to validate this
      locale:'pt',
      defaultView: 'dayGridDay',
      firstDay: (new Date().getDay())-1,
      scrollTime: scrollTime,
      nowIndicator: true,
      defaultDate: new Date(),
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      eventLimit: true, // allow "more" link when too many events,
      eventOverlap: true,
      selectMirror: true,
      selectable: true,
      displayEventTime: false,
      eventResize: updateEventEndOnDB,
      eventDrop: updateEventOnDB,
      eventRender: function(info) {
        var tooltip = new Tooltip(info.el, {
          title: info.event.extendedProps.description,
          placement: 'top',
          trigger: 'hover',
          container: 'body'
        });
      },
      events: {
        id: 'scheduleevents',
        url: 'getEvents.php'
      }
    });

    window.jscalendar.render();
  });

</script>