<div id="chart-container" style="width:100%; height:400px;"></div>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var chart = new Highcharts.Chart({
        title: {
            text: 'Mudanças por dia'
        },
        chart: {
            renderTo: 'chart-container',
            zoomType: 'xy',
            backgroundColor: '#f2e6ff',
            type: 'line'
        },
        xAxis: {
            type: 'datetime',
            title: {
                text: "Dia"
            },
            dateTimeLabelFormats: {
                day: '%e-%b-%Y'
            }
        },
        yAxis: {
            title: {
                text: "N.º mudanças"
            }
        },
        series: [{
            name: 'N.º mudanças/Dia',
            data: [<?php echo join($data1); ?>]
        },{
            name: 'N.º cancelamentos/Dia',
            data: [<?php echo join($data2); ?>],
            color: '#FF0000'
            }
        ]
    });
});
</script>
<div class="text-right mb-2 mt-5">
    <a href="?page=schedulesEdit"><button type="button" class="btn btn-primary btn-sm"><i
                class="fas fa-plus-circle"></i>Nova Marcação</button></a>
</div>
<h2>Mudanças a decorrer</h2>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Início</th>
                <th scope="col">Fim</th>
                <th scope="col">Morada de Carga</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($schedules["ongoing"] AS $schedule) {
                    echo '<tr class="table-row" data-href="?page=schedulesEdit&Id='.$schedule['Id'].'">';
                    echo '<td>'.$schedule['Start'].'</td>';
                    echo '<td>'.$schedule['End'].'</td>';
                    echo '<td>'.$schedule['Address'].'</td>';
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
    <?php            
        if(empty($schedules["ongoing"])){
            echo '<tr><td><div class="blank-slate">Não há Marcações a decorrer...</div></td></tr>';
        }
    ?>
</div>
<h2 class="mt-3">Próximas Marcações</h2>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Início</th>
                <th scope="col">Fim</th>
                <th scope="col">Morada de Carga</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($schedules["future"] AS $schedule) {
                    echo '<tr class="table-row" data-href="?page=schedulesEdit&Id='.$schedule['Id'].'">';
                    echo '<td>'.$schedule['Start'].'</td>';
                    echo '<td>'.$schedule['End'].'</td>';
                    echo '<td>'.$schedule['Address'].'</td>';
                    echo '<td><a onclick="return confirm(\'Tem a certeza que pretende cancelar a marcação?\')" title="Cancelar marcação" href="?page=schedulesCancel&origin=home&Id='.$schedule['Id'].'"><i class="text-danger fas fa-times"></i></a>';
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
    <?php            
        if(empty($schedules["future"])){
            echo '<tr><td><div class="blank-slate">Não há próximas Marcações...</div></td></tr>';
        }
    ?>
</div>