<div id='calendar-container'>
    <div id='calendar'></div>
</div>
<script>

  document.addEventListener('DOMContentLoaded', function() {
    function getEvents() {
        return [
          <?php echo getSchedulesCalendar($db);?>
      ];
    }
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'interaction', 'dayGrid', 'timeGrid', 'list' ],
      height: 'parent',
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      },
      locale:'pt',
      defaultView: 'dayGridMonth',
      defaultDate: new Date(),
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      eventLimit: true, // allow "more" link when too many events
      events: getEvents()
    });

    calendar.render();
  });

</script>