<form action="?page=schedules" method="post">
<div class="mt-1 card-body row no-gutters align-items-center">
    <div class="col-auto">
        <i class="fas fa-search h5 text-body"></i>
    </div>
    <!--end of col-->
    <div class="col-sm-4">
        <input value="<?php echo $search?>" name="search" id="search" class="form-control form-control-borderless" type="search" placeholder="Indique um critério de pesquisa...">
    </div>
    <!--end of col-->
    <div class="col-sm-5">
        <button class="btn btn-primary" name="submitbutton" value="search" type="submit">Pesquisar</button>
        <button name="submitbutton" value="clear" class="btn btn bg-light" type="submit">Limpar</button>
    </div>
    <!--end of col-->
</div>
</form>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Início</th>
                <th scope="col">Fim</th>
                <th scope="col">Carga</th>
                <th scope="col">Descarga</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($schedules['list'] AS $schedule) {
                    echo '<tr class="table-row" data-href="?page=schedulesEdit&Id='.$schedule['Id'].'">';
                    echo '<td>'.$schedule['Start'].'</td>';
                    echo '<td>'.$schedule['End'].'</td>';
                    echo '<td>'.$schedule['Address'].'</td>';
                    echo '<td>'.$schedule['EndAddress'].'</td>';
                    echo '<td class="text-danger">'.($schedule['IsCanceled']==1?"Cancelada</td>":'<a title="Cancelar Mudança" onclick="return confirm(\'Tem a certeza que pretende cancelar a Mudança?\')" href="?page=schedulesCancel&origin=schedules&Id='.$schedule['Id'].'"><i class="text-danger fas fa-times"></i></a></td>');
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
    <?php            
        if(empty($schedules)){
            echo '<tr><td><div class="blank-slate">Não há Marcações registadas...</div></td></tr>';
        }
    ?>

    <nav aria-label="Page navigation" class="pagination-nav">
        <ul class="pagination">
            <?php 
                $maxpage = ceil($schedules['count']/$linecount);
                if($listpage>0){
                    echo '<li class="page-item">
                    <a class="page-link" href="?page=schedules&listpage='.($listpage-1).'" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                    </li>';
                }
                for($i=1;$i<=$maxpage;$i++){
                    echo '<li class="page-item"><a class="page-link '.($i==$listpage+1?'page-link-active':'').'" href="?page=schedules&listpage='.($i-1).'">'.$i.'</a></li>';
                }
                if(($listpage+1)<$maxpage){
                    echo '
                    <li class="page-item">
                    <a class="page-link" href="?page=schedules&listpage='.($listpage+1).'" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                    </li>';
                }
            ?>
        </ul>
    </nav>
</div>