<div class="justify-content-center align-items-center mb-5">
    <form action="?page=schedulesEdit" method="post">
        <h1 data-spy="affix" data-offset-top="500">Nova Mudança</h1>
        <div class="row">
            <div class="col justify-content-center align-items-center">
                <div class="form-group">
                    <label for="client">Cliente</label>
                    <textarea class="form-control" name="client" id="client"
                        placeholder="Introduza o Cliente" required><?php echo (!empty($scheduleData["schedule"]["client"]))?$scheduleData["schedule"]["client"]:'';?></textarea>
                </div>
                <div class="form-group">
                    <label for="start">Início</label>
                    <input type="text" class="form-control" name="start" id="datetimepickerstart"
                        value="<?php echo (!empty($scheduleData["schedule"]["start"]))?date_format(date_create($scheduleData["schedule"]["start"]), 'd/m/Y H:i'):'';?>"
                        placeholder="Selecione a data e a hora a que começa a mudança" required>
                </div>
                <div class="form-group">
                    <label for="duration">Duração(h)</label>
                    <input type="number" class="form-control" name="duration" id="duration"
                        value="<?php echo(!empty($scheduleData["schedule"]["end"]))?differenceInHours($scheduleData["schedule"]["start"],$scheduleData["schedule"]["end"]):'';?>"
                        placeholder="Introduza a duração prevista"
                        required
                    >
                </div>
                <div class="form-group">
                    <label for="address">Morada de carga</label>
                    <textarea class="form-control" name="address" id="address"
                        placeholder="Introduza a morada de carga" required><?php echo (!empty($scheduleData["schedule"]["address"]))?$scheduleData["schedule"]["address"]:'';?></textarea>
                </div>
                <div class="form-group">
                    <label for="endaddress">Morada de descarga</label>
                    <textarea class="form-control" name="endaddress" id="endaddress"
                        placeholder="Introduza a morada de descarga" required><?php echo (!empty($scheduleData["schedule"]["endaddress"]))?$scheduleData["schedule"]["endaddress"]:'';?></textarea>
                </div>
                <input type="number" name="id" id="id" value="<?php echo $scheduleData["schedule"]["id"];?>" class="d-none">
            </div>
            <div class="col align-top">
                <div class="form-group">
                    <label for="nif">NIF</label>
                    <input type="number" class="form-control" name="nif" id="nif" value="<?php echo (!empty($scheduleData["schedule"]["nif"]))?$scheduleData["schedule"]["nif"]:'';?>"
                        placeholder="Introduza o NIF">
                </div>
                <div class="form-group">
                    <label for="cars">Carros</label>
                    <div id="carsOptions">
                        <select name="cars[]" id="cars-multipleselect" class="" aria-labelledby="dropdownMenuButton"
                            multiple="multiple" required>
                            <?php
                                foreach($scheduleData["carsAvailable"] AS $car) {
                                    echo '<option '.((isArrayValueInArrayOfArray($scheduleData["scheduleCars"],[$car["Id"]]))?"selected":"").' value="'.$car["Id"].'">'.$car["Number"].' ( '.$car['Plate'].' '.$car['Maker'].' '.$car['Model'].' )</option>';
                                }
                            ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="workers">Funcionários</label>
                    <div id="workersOptions">
                        <select name="workers[]" id="workers-multipleselect" class="" aria-labelledby="dropdownMenuButton"
                            multiple="multiple" required>
                            <?php
                                foreach($scheduleData["workersAvailable"] AS $worker) {
                                    echo '<option '.((isArrayValueInArrayOfArray($scheduleData["scheduleWorkers"],[$worker["Id"]]))?"selected":"").' value="'.$worker["Id"].'">'.$worker["Name"].'</option>';
                                }
                            ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                <label for="notes">Notas</label>
                    <textarea class="form-control" name="notes" id="notes"
                        placeholder="Introduza as suas notas"><?php echo (!empty($scheduleData["schedule"]["notes"]))?$scheduleData["schedule"]["notes"]:'';?></textarea>
                </div>
                <div class="checkbox">
                    <label style="font-size: 1.5em">
                        <input onchange="autosubmit('schedulesubmit');" type="checkbox" 
                            class="custom-control-input" name="ispaid" id="ispaid"
                            <?php echo (!empty($scheduleData["schedule"]["ispaid"])?'checked':'')?>
                        >
                        <span class="cr"><i class="cr-icon fas fa-euro-sign"></i></span>
                        Pago
                    </label>
                </div>
                <div class="checkbox">
                    <label style="font-size: 1.5em">
                        <input onchange="autosubmit('schedulesubmit');" type="checkbox" 
                            class="custom-control-input" name="isclosed" id="isclosed"
                            <?php 
                                echo (!empty($scheduleData["schedule"]["isclosed"])?'checked disabled':'');
                            ?>
                        >
                        <span class="cr"><i class="cr-icon fas fa-check"></i></span>
                        Terminou
                    </label>
                </div>
            </div>
        </div>
        <input type="hidden" name="wasclosed" 
            value="<?php echo $scheduleData["schedule"]["isclosed"];?>"
        >
        <button id="schedulesubmit" type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>