<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>TCCSantana Schedule</title>

    <link rel="icon" type="image/png" href="favicon.png">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../app/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="../app/css/multiselect.css">
    <link href='../app/packages/core/main.css' rel='stylesheet' />
    <link href='../app/packages/daygrid/main.css' rel='stylesheet' />
    <link href='../app/packages/timegrid/main.css' rel='stylesheet' />
    <link href='../app/packages/list/main.css' rel='stylesheet' />
    <link href='../app/packages/bootstrap/main.css' rel='stylesheet' />
    <link href='../app/packages/daygrid/main.css' rel='stylesheet' />

    <style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
    </style>
    <!-- Custom styles for this template -->
    <link href="style.css" rel="stylesheet">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.highcharts.com/highcharts.js"></script>
</head>

<body class="d-flex flex-column h-100">
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="navbar-brand" href="#">TCCSantana</div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item <?php echo isActive($page,'home');?>">
                        <a class="nav-link" href="?page=home"><i class="fas fa-home"></i>Início</a>
                    </li>
                    <li class="nav-item <?php echo isActive($page,'daily');?>">
                        <a class="nav-link" href="?page=daily"><i class="fas fa-calendar-day"></i>Diário</a>
                    </li>
                    <li class="nav-item <?php echo isActive($page,'resume');?>">
                        <a class="nav-link" href="?page=resume"><i class="fas fa-chart-line"></i>Resumo</a>
                    </li>
                    <li class="nav-item <?php echo isActive($page,'schedules');?>">
                        <a class="nav-link" href="?page=schedules"><i class="fas fa-calendar-check"></i>Histórico</a>
                    </li>
                    <li class="nav-item <?php echo isActive($page,'workers').isActive($page,'workersEdit');?>">
                        <a class="nav-link" href="?page=workers"><i class="fas fa-users"></i>Funcionários</a>
                    </li>
                    <li class="nav-item <?php echo isActive($page,'cars').isActive($page,'carsEdit') ;?>">
                        <a class="nav-link" href="?page=cars"><i class="fas fa-truck"></i>Carros</a>
                    </li>
                    <li class="nav-item <?php echo isActive($page,'schedulesEdit');?>">
                        <a class="nav-link" href="?page=schedulesEdit"><i class="fas fa-plus-circle"></i>Nova Mudança</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="flex-shrink-0">
        <div class="container">
            <?php
                if(!empty($_GET['message']))
                    include('feedback.phtml');
            ?>
            <script type="text/javascript">
                
                setInterval(function(){
                    $(".alert.show").removeClass('show');
                },3000);

                function autosubmit(submitbutton){
                    setTimeout(function(){
                        $('#'+submitbutton).click();
                    },1000);
                    
                }

            </script>
            <?php include($main_content); ?>
        </div>
    </main>

    <footer class="footer mt-auto py-3 fixed-bottom">
        <div class="container">
            <span>&copy Transportadora do Campo Santana</span>
        </div>
    </footer>
    <script src="../app/scripts/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js" type="text/javascript"></script>
    <script src="../app/scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="../app/scripts/moment-timezone.min.js"></script>
    <script src="../app/scripts/pt.js"></script>
    <script src="../app/scripts/multiselect.js"></script>
    <script src="../app/scripts/popper.js"></script>
    <script src="../app/scripts/popper-utils.js"></script>
    <script src="../app/scripts/tooltip.js"></script>
    <script src="../app/scripts/bootstrap.min.js"></script>
    <script src='../app/packages/core/main.js'></script>
    <script src='../app/packages/core/locales-all.js'></script>
    <script src='../app/packages/interaction/main.js'></script>
    <script src='../app/packages/daygrid/main.js'></script>
    <script src='../app/packages/timegrid/main.js'></script>
    <script src='../app/packages/list/main.js'></script>
    <script src='../app/packages/bootstrap/main.js'></script>
    <script src='../app/packages/daygrid/main.js'></script>
    <script src="script.js"></script>
</body>

</html>