<div class="text-right mb-2 mt-5">
    <a href="?page=workersEdit"><button type="button" class="btn btn-primary btn-sm"><i
                class="fas fa-plus-circle"></i>Novo Funcionário</button></a>
</div>
<div class="table-responsive">
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Telefone/Telemóvel</th>
                <th scope="col">email</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($workers AS $worker) {
                    echo '<tr class="table-row" data-href="?page=workersEdit&Id='.$worker['Id'].'">';
                    echo '<td>'.$worker['Name'].'</td>';
                    echo '<td>'.$worker['Phone'].'</td>';
                    echo '<td>'.$worker['Email'].'</td>';
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
    <?php            
        if(empty($workers)){
            echo '<tr><td><div class="blank-slate">Não há Funcionários registados...</div></td></tr>';
        }
    ?>
</div>