<form action="?page=workers" method="post">
<div class="mt-1 card-body row no-gutters align-items-center">
    <div class="col-auto">
        <i class="fas fa-search h5 text-body"></i>
    </div>
    <!--end of col-->
    <div class="col-sm-4">
        <input value="<?php echo $search?>" name="search" id="search" class="form-control form-control-borderless" type="search" placeholder="Indique um critério de pesquisa...">
    </div>
    <!--end of col-->
    <div class="col-sm-5">
        <button class="btn btn-primary" name="submitbutton" value="search" type="submit">Pesquisar</button>
        <button name="submitbutton" value="clear" class="btn btn bg-light" type="submit">Limpar</button>
    </div>
    <!--end of col-->
    <div class="col-sm-2 text-right">
        <a href="?page=workersEdit"><button type="button" class="btn btn-primary btn-sm"><i
                class="fas fa-plus-circle"></i>Novo Funcionário</button></a>
    </div>
</div>
</form>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Telefone/Telemóvel</th>
                <th scope="col">email</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($workers['list'] AS $worker) {
                    echo '<tr class="table-row" data-href="?page=workersEdit&Id='.$worker['Id'].'">';
                    echo '<td>'.$worker['Name'].'</td>';
                    echo '<td>'.$worker['Phone'].'</td>';
                    echo '<td>'.$worker['Email'].'</td>';
                    echo '<td class="text-danger"><a onclick="return confirm(\'Tem a certeza que pretende eliminar o funcionário?\')" title="Eliminar carro" href="?page=workersDelete&origin=workers&Id='.$worker['Id'].'"><i class="text-danger fas fa-trash-alt"></i></a></td>';
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
    <?php            
        if(empty($workers)){
            echo '<tr><td><div class="blank-slate">Não há Funcionários registados...</div></td></tr>';
        }
    ?>

    <nav aria-label="Page navigation" class="pagination-nav">
        <ul class="pagination">
            <?php 
                $maxpage = ceil($workers['count']/$linecount);
                if($listpage>0){
                    echo '<li class="page-item">
                    <a class="page-link" href="?page=workers&listpage='.($listpage-1).'" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                    </li>';
                }
                for($i=1;$i<=$maxpage;$i++){
                    echo '<li class="page-item"><a class="page-link '.($i==$listpage+1?'page-link-active':'').'" href="?page=workers&listpage='.($i-1).'">'.$i.'</a></li>';
                }
                if(($listpage+1)<$maxpage){
                    echo '
                    <li class="page-item">
                    <a class="page-link" href="?page=workers&listpage='.($listpage+1).'" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                    </li>';
                }
            ?>
        </ul>
    </nav>
</div>