<div class="justify-content-center align-items-center">
<form action="?page=workersEdit" method="post">
    <div class="row justify-content-center align-items-center">
        <div class="col text-center">
            <img src="<?php echo $config["ICONS_PATH"].'icons8-user-100.png'?>" alt="funcionário">
        </div>
        <div class="col">
            <h1>Novo Funcionário</h1>
            <div class="form-group">
                <label for="name">Nome</label>
                <input maxlength="250" type="text" class="form-control" name="name" id="name"  value="<?php echo (!empty($worker["name"]))?$worker["name"]:'';?>" placeholder="Introduza o Nome" required>
            </div>
            <div class="form-group">
                <label for="phone">Telefone/Telmóvel</label>
                <input maxlength="9" type="text" class="form-control" name="phone" id="phone"  value="<?php echo (!empty($worker["phone"]))?$worker["phone"]:'';?>" placeholder="Introduza o n.º de Telefone ou Telemóvel">
            </div>
            <div class="form-group">
                <label for="email">email</label>
                <input maxlength="50" type="email" class="form-control" name="email" id="email"  value="<?php echo (!empty($worker["email"]))?$worker["email"]:'';?>" placeholder="Introduza o email">
            </div>
            <input type="number" name="id" id="id" value="<?php echo $worker["id"];?>" class="d-none">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </div>
</form>
</div>