<div class="text-right mb-2 mt-1">
    <a href="?page=workersEdit"><button type="button" class="btn btn-primary btn-sm"><i
                class="fas fa-plus-circle"></i>Novo Funcionário</button></a>
</div>
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Telefone/Telemóvel</th>
                <th scope="col">email</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($workers AS $worker) {
                    echo '<tr class="table-row" data-href="?page=workersEdit&Id='.$worker['Id'].'">';
                    echo '<td>'.$worker['Name'].'</td>';
                    echo '<td>'.$worker['Phone'].'</td>';
                    echo '<td>'.$worker['Email'].'</td>';
                    echo '<td class="text-danger"><a onclick="return confirm(\'Tem a certeza que pretende eliminar o funcionário?\')" title="Eliminar carro" href="?page=workersDelete&origin=workers&Id='.$worker['Id'].'"><i class="text-danger fas fa-trash-alt"></i></a></td>';
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
    <?php            
        if(empty($workers)){
            echo '<tr><td><div class="blank-slate">Não há Funcionários registados...</div></td></tr>';
        }
    ?>
</div>